/** Marker comments used to identify the Lens Studio managed AGENTS.md region. */
export const AGENTS_MD_MANAGED_START = "<!-- BEGIN Lens Studio managed AGENTS block -->";
export const AGENTS_MD_MANAGED_END = "<!-- END Lens Studio managed AGENTS block -->";
export const AGENTS_MD_DISCLAIMER =
    "<!-- Auto-generated by Lens Studio. Changes inside this block will be overwritten. Add custom content outside this block. -->";

/** Legacy marker used by earlier Agents-Docs implementations. */
export const AGENTS_MD_LEGACY_MARKER = "<!-- Shipped by Lens Studio -->";
export const AGENTS_MD_LEGACY_DISCLAIMER =
    "<!-- Auto-generated. Do not modify - changes overwritten. Add custom content outside this section. -->";

export interface ManagedAgentsMdSections {
    before: string;
    after: string;
}

function trimSection(content: string): string {
    return content.trim();
}

/**
 * Parse an AGENTS.md file and return the user-owned content outside Lens Studio's
 * managed region. Returns null when the file is user-owned or markers are malformed.
 */
export function extractManagedSections(existingContent: string | null): ManagedAgentsMdSections | null {
    if (existingContent === null) {
        return { before: "", after: "" };
    }

    const content = existingContent.trim();
    if (content.length === 0) {
        return { before: "", after: "" };
    }

    const managedStartIdx = existingContent.indexOf(AGENTS_MD_MANAGED_START);
    const managedEndIdx = existingContent.indexOf(AGENTS_MD_MANAGED_END);

    if (managedStartIdx !== -1 || managedEndIdx !== -1) {
        if (managedStartIdx === -1 || managedEndIdx === -1 || managedEndIdx < managedStartIdx) {
            return null;
        }

        const before = trimSection(existingContent.substring(0, managedStartIdx));
        const after = trimSection(
            existingContent.substring(managedEndIdx + AGENTS_MD_MANAGED_END.length)
        );

        return { before, after };
    }

    const legacyFirstIdx = existingContent.indexOf(AGENTS_MD_LEGACY_MARKER);
    if (legacyFirstIdx === -1) {
        return null;
    }

    const legacyLastIdx = existingContent.lastIndexOf(AGENTS_MD_LEGACY_MARKER);
    if (legacyLastIdx === legacyFirstIdx) {
        const before = trimSection(existingContent.substring(0, legacyFirstIdx));
        return { before, after: "" };
    }

    const before = trimSection(existingContent.substring(0, legacyFirstIdx));
    const after = trimSection(existingContent.substring(legacyLastIdx + AGENTS_MD_LEGACY_MARKER.length));

    return { before, after };
}

export function buildManagedAgentsMd(
    generatedContent: string,
    sections: ManagedAgentsMdSections = { before: "", after: "" }
): string {
    const parts: string[] = [];

    if (sections.before.length > 0) {
        parts.push(sections.before);
    }

    parts.push(AGENTS_MD_MANAGED_START);
    parts.push(AGENTS_MD_DISCLAIMER);
    parts.push(generatedContent.trim());
    parts.push(AGENTS_MD_MANAGED_END);

    if (sections.after.length > 0) {
        parts.push(sections.after);
    }

    return parts.join("\n\n") + "\n";
}

/**
 * Build the next AGENTS.md content if Lens Studio owns a managed region in the file.
 * Returns null when the file is user-owned or has malformed managed markers.
 */
export function mergeAgentsMd(existingContent: string | null, generatedContent: string): string | null {
    const sections = extractManagedSections(existingContent);
    if (sections === null) {
        return null;
    }

    return buildManagedAgentsMd(generatedContent, sections);
}

/**
 * Describe why mergeAgentsMd would leave an existing AGENTS.md unchanged.
 * Returns null when Lens Studio can safely create or update its managed block.
 */
export function getAgentsMdMergeFailureMessage(existingContent: string | null): string | null {
    if (extractManagedSections(existingContent) !== null) {
        return null;
    }

    const content = existingContent ?? "";
    if (content.includes(AGENTS_MD_MANAGED_START) || content.includes(AGENTS_MD_MANAGED_END)) {
        return "existing AGENTS.md has malformed Lens Studio managed markers; AGENTS.md was not injected.";
    }

    return "existing AGENTS.md has no Lens Studio managed block and appears user-owned; AGENTS.md was not injected.";
}
