import * as FileSystem from "LensStudio:FileSystem";

import { extractProjectName, buildServerName } from "../mcpUtils.js";
import {
    parseSettings,
    mergePermissions,
    serializeSettings
} from "../settingsUtils.js";

/** Entries the plugin ensures are present in the project's .gitignore. */
const GITIGNORE_ENTRIES = [
    ".mcp.json",
    ".cursor/mcp.json",
    ".vscode/mcp.json",
    ".codex/config.toml",
    ".claude/settings.local.json",
];

/**
 * Create CLAUDE.md at the project root if one doesn't already exist.
 * Seeds it with "@AGENTS.md" so AI coding agents automatically read
 * the plugin-injected AGENTS.md documentation.
 */
export function ensureInstructionsMd(projectDir: Editor.Path): void {
    const instructionsMdPath = projectDir.appended(new Editor.Path("CLAUDE.md"));

    if (FileSystem.exists(instructionsMdPath)) {
        return;
    }

    try {
        FileSystem.writeFile(instructionsMdPath, "@AGENTS.md\n");
        console.log("[AgentsDocs] Created CLAUDE.md with @AGENTS.md directive", console.None);
    } catch (e) {
        console.error("[AgentsDocs] Error creating CLAUDE.md:", e, console.None);
    }
}

/**
 * Ensure the project's .gitignore contains entries for auto-generated
 * MCP config files. Creates the file if missing, or appends only the
 * entries not already present.
 */
export function ensureGitignore(projectDir: Editor.Path): void {
    const gitignorePath = projectDir.appended(new Editor.Path(".gitignore"));

    try {
        let existing = "";
        if (FileSystem.exists(gitignorePath)) {
            existing = FileSystem.readFile(gitignorePath);
        }

        const existingLines = new Set(
            existing.split("\n").map(l => l.trim())
        );

        const missing = GITIGNORE_ENTRIES.filter(
            entry => !existingLines.has(entry)
        );

        if (missing.length === 0) {
            return;
        }

        let content = existing;
        if (content.length > 0) {
            if (!content.endsWith("\n")) {
                content += "\n";
            }
            content += "\n";
        }
        content += "# Auto-generated by Lens Studio (Agents-Docs plugin)\n";
        content += missing.join("\n") + "\n";

        FileSystem.writeFile(gitignorePath, content);
        console.log("[AgentsDocs] Updated .gitignore with MCP ignore rules", console.None);
    } catch (e) {
        console.error("[AgentsDocs] Error updating .gitignore:", e, console.None);
    }
}

/**
 * Update .claude/settings.local.json with MCP permission configuration.
 * Reads existing file if present, merges the Lens Studio MCP permission
 * allowlist, and writes back. Preserves all other settings.
 */
export function injectClaudeSettings(projectDir: Editor.Path, projectFile: Editor.Path): void {
    try {
        const claudeDir = projectDir.appended(new Editor.Path(".claude"));
        const settingsPath = claudeDir.appended(new Editor.Path("settings.local.json"));

        // Read existing content (may not exist)
        let existingContent: string | null = null;
        if (FileSystem.exists(settingsPath)) {
            existingContent = FileSystem.readFile(settingsPath);
        }

        // Parse, merge MCP permissions, serialize
        const settings = parseSettings(existingContent);
        // Temporarily disable extraKnownMarketplaces injection. When this is
        // re-enabled, import mergeMarketplace and use the marketplace repo
        // lens-studio-devs/ls-agent-extensions.
        // let merged = mergeMarketplace(settings);
        let merged = settings;

        const projectName = extractProjectName(projectFile);
        if (projectName) {
            const serverName = buildServerName(projectName);
            merged = mergePermissions(merged, serverName);
        }

        const output = serializeSettings(merged);

        // Ensure .claude/ directory exists
        if (!FileSystem.exists(claudeDir)) {
            FileSystem.createDir(claudeDir, { recursive: true });
        }

        FileSystem.writeFile(settingsPath, output);
        console.log("[AgentsDocs] Updated .claude/settings.local.json with MCP permissions", console.None);
    } catch (e) {
        console.error("[AgentsDocs] Error updating Claude settings:", e, console.None);
    }
}
