import * as FileSystem from "LensStudio:FileSystem";

import { extractProjectName, buildServerName } from "../mcpUtils.js";
import {
    parseSettings,
    mergePermissions,
    serializeSettings
} from "../settingsUtils.js";

/** Entries the plugin ensures are present in the project's .gitignore. */
const GITIGNORE_ENTRIES = [
    ".mcp.json",
    ".cursor/mcp.json",
    ".vscode/mcp.json",
    ".codex/config.toml",
    ".claude/settings.local.json",
];

/** Marker comments delimiting the Lens Studio managed region of .gitignore. */
const GITIGNORE_MANAGED_START = "# BEGIN Lens Studio managed Agents-Docs block";
const GITIGNORE_MANAGED_END = "# END Lens Studio managed Agents-Docs block";

/**
 * Header written by older plugin versions that appended entries without a
 * closing marker. Detected so those loose entries can be migrated into the
 * managed block instead of being left behind as duplicates.
 */
const GITIGNORE_LEGACY_HEADER = "# Auto-generated by Lens Studio (Agents-Docs plugin)";

function detectLineEnding(value: string): "\n" | "\r\n" {
    return value.includes("\r\n") ? "\r\n" : "\n";
}

function startsWithLineBreak(value: string): boolean {
    return value.startsWith("\n") || value.startsWith("\r\n");
}

/** Build the managed block: start marker, the entries, end marker. */
function buildManagedGitignoreBlock(eol: string): string {
    return [GITIGNORE_MANAGED_START, ...GITIGNORE_ENTRIES, GITIGNORE_MANAGED_END].join(eol);
}

/**
 * Remove the legacy un-delimited section (the `# Auto-generated...` header plus
 * the consecutive managed-entry lines that followed it) so its contents can be
 * re-emitted inside the managed block. Lines the plugin doesn't own are kept.
 */
function stripLegacyGitignoreBlock(content: string, eol: string): string {
    const entrySet = new Set<string>(GITIGNORE_ENTRIES);
    const lines = content.split(/\r?\n/);
    const out: string[] = [];

    for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim() === GITIGNORE_LEGACY_HEADER) {
            // Skip the header and any consecutive lines that are managed entries.
            let j = i + 1;
            while (j < lines.length && entrySet.has(lines[j].trim())) {
                j++;
            }
            i = j - 1;
            continue;
        }
        out.push(lines[i]);
    }

    return out.join(eol);
}

/**
 * Compute the desired .gitignore content: a single managed block whose body is
 * exactly GITIGNORE_ENTRIES. Replaces an existing managed region in place,
 * migrates a legacy un-delimited section, or appends a fresh block — never
 * touching content outside the markers. Returns null if the file contains
 * malformed managed markers (so the caller can skip rather than corrupt it).
 */
function mergeGitignore(existingContent: string): string | null {
    const eol = detectLineEnding(existingContent);
    const block = buildManagedGitignoreBlock(eol);
    const content = stripLegacyGitignoreBlock(existingContent, eol);

    const startIndex = content.indexOf(GITIGNORE_MANAGED_START);
    const endIndex = content.indexOf(GITIGNORE_MANAGED_END);

    if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
        // Replace the existing managed region, preserving surrounding content.
        const before = content.slice(0, startIndex);
        const after = content.slice(endIndex + GITIGNORE_MANAGED_END.length);

        let merged = before;
        if (merged.length > 0 && !merged.endsWith("\n")) {
            merged += eol;
        }
        merged += block;
        if (after.length > 0 && !startsWithLineBreak(after)) {
            merged += eol;
        }
        merged += after;
        if (!merged.endsWith("\n")) {
            merged += eol;
        }
        return merged;
    }

    // Exactly one marker present, or end before start → malformed; refuse to edit.
    if (startIndex !== -1 || endIndex !== -1) {
        return null;
    }

    // No managed region yet → append a fresh block after existing content.
    const trimmed = content.replace(/[\r\n]+$/, "");
    if (trimmed.trim().length === 0) {
        return block + eol;
    }
    return trimmed + eol + eol + block + eol;
}

/**
 * Create CLAUDE.md at the project root if one doesn't already exist.
 * Seeds it with "@AGENTS.md" so AI coding agents automatically read
 * the plugin-injected AGENTS.md documentation.
 */
export function ensureInstructionsMd(projectDir: Editor.Path): void {
    const instructionsMdPath = projectDir.appended(new Editor.Path("CLAUDE.md"));

    if (FileSystem.exists(instructionsMdPath)) {
        return;
    }

    try {
        FileSystem.writeFile(instructionsMdPath, "@AGENTS.md\n");
        console.log("[AgentsDocs] Created CLAUDE.md with @AGENTS.md directive", console.None);
    } catch (e) {
        console.error("[AgentsDocs] Error creating CLAUDE.md:", e, console.None);
    }
}

/**
 * Ensure the project's .gitignore contains entries for auto-generated
 * MCP config files, confined to a marker-delimited managed block. The plugin
 * only ever rewrites the region between its BEGIN/END markers (migrating the
 * legacy un-delimited section into it on first run); all other content the
 * developer added is preserved verbatim.
 */
export function ensureGitignore(projectDir: Editor.Path): void {
    const gitignorePath = projectDir.appended(new Editor.Path(".gitignore"));

    try {
        let existing = "";
        if (FileSystem.exists(gitignorePath)) {
            existing = FileSystem.readFile(gitignorePath);
        }

        const merged = mergeGitignore(existing);

        if (merged === null) {
            console.error("[AgentsDocs] .gitignore has malformed managed markers; skipping update", console.None);
            return;
        }

        // Idempotent: skip the write when the managed block is already current.
        if (merged === existing) {
            return;
        }

        FileSystem.writeFile(gitignorePath, merged);
        console.log("[AgentsDocs] Updated .gitignore managed block", console.None);
    } catch (e) {
        console.error("[AgentsDocs] Error updating .gitignore:", e, console.None);
    }
}

/**
 * Update .claude/settings.local.json with MCP permission configuration.
 * Reads existing file if present, merges the Lens Studio MCP permission
 * allowlist, and writes back. Preserves all other settings.
 */
export function injectClaudeSettings(projectDir: Editor.Path, projectFile: Editor.Path): void {
    try {
        const claudeDir = projectDir.appended(new Editor.Path(".claude"));
        const settingsPath = claudeDir.appended(new Editor.Path("settings.local.json"));

        // Read existing content (may not exist)
        let existingContent: string | null = null;
        if (FileSystem.exists(settingsPath)) {
            existingContent = FileSystem.readFile(settingsPath);
        }

        // Parse, merge MCP permissions, serialize
        const settings = parseSettings(existingContent);
        // Temporarily disable extraKnownMarketplaces injection. When this is
        // re-enabled, import mergeMarketplace and use the marketplace repo
        // lens-studio-devs/ls-agent-extensions.
        // let merged = mergeMarketplace(settings);
        let merged = settings;

        const projectName = extractProjectName(projectFile);
        if (projectName) {
            const serverName = buildServerName(projectName);
            merged = mergePermissions(merged, serverName);
        }

        const output = serializeSettings(merged);

        // Ensure .claude/ directory exists
        if (!FileSystem.exists(claudeDir)) {
            FileSystem.createDir(claudeDir, { recursive: true });
        }

        FileSystem.writeFile(settingsPath, output);
        console.log("[AgentsDocs] Updated .claude/settings.local.json with MCP permissions", console.None);
    } catch (e) {
        console.error("[AgentsDocs] Error updating Claude settings:", e, console.None);
    }
}
